### ISSUE TITLE
A request

### ISSUE THREAD

**Issue by ghost** [DefJia/Auto_Reservation_System_BE#12]
Hi, I am a BITer who entered this school in 2020 and now, a CSer.
I am interested in this project and wonder more details.
The request for the communicating  QQ group had been sent.
(I want to change it to **JAVA** )

**Comment by DefJia** [comment]
Hi! I am glad and surprised that someone is still interested in this project after my graduation. Well, welcome to join us and devote ourselves to the development and innovation of this project together. 
You may send the request on QQ again because I didn't receive it just now for unknown problems.
